version: '3.8'

services:
  loan-app:
    build: .
    container_name: loan_risk_prediction
    ports:
      - "8501:8501"
    volumes:
      - ./data:/app/data
      - ./models:/app/models
    restart: unless-stopped